# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[status]
disabled = false
symbol = ''

[sudo]
disabled = false
format = "[$symbol]($style) "
symbol = "⚡️"

