# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
style = 'blue'

[status]
disabled = false
symbol = ''

[sudo]
disabled = false
format = "[$symbol]($style) "
symbol = "⚡️"

[git_branch]
style = 'bold bright-black'

[docker_context]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true
