export EDITOR=$VISUAL
export VISUAL='mvim -f'

export LESS='-F -g -i -M -R -w -X -z-4'
export PATH="$PATH:/usr/sbin:/sbin"

if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/bin/brew shellenv)"
fi

# For compiling Ruby gems
# export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export IRB_HISTFILE=~/.irb_history

PATH=$(cat <<-EOF | tr "\n" ':' | sed 's/:*$//g'
$HOME/bin
$HOME/.files/bin
$HOMEBREW_PREFIX/lib/ruby/gems/3.0.0/bin
$(echo $HOME/Library/Python/*/bin | sed 's/ /:/g')
$HOMEBREW_PREFIX/opt/ruby/bin
$HOMEBREW_PREFIX/opt/libpq/bin
/usr/local/sbin
$PATH
EOF
)
export PATH

export BAT_STYLE=plain

source ~/.files/zsh/alias.zsh
source ~/.files/zsh/fzf_env.zsh
